using System;
using System.IO;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

/// <summary>
/// Regenerates Assets/Resources/BuildInfo.txt before every player build, bumping
/// the build number by one. <c>DevBuildStamp</c> reads that asset at runtime to
/// draw the on-screen stamp in development builds.
///
/// The number lives in the asset itself (not EditorPrefs) so it is committed and
/// stays consistent across machines and CI.
/// </summary>
public sealed class BuildStampGenerator : IPreprocessBuildWithReport
{
    private const string ResourcesFolder = "Assets/Resources";
    private const string AssetPath = ResourcesFolder + "/" + DevBuildStamp.ResourceName + ".txt";

    public int callbackOrder => 0;

    public void OnPreprocessBuild(BuildReport report)
    {
        int build = Write(Read().Build + 1, report.summary.platform.ToString());
        Debug.Log($"[BuildStamp] v{PlayerSettings.bundleVersion} build {build:D2} " +
                  $"({report.summary.platform}) — stamp is {(IsDevelopmentBuild(report) ? "visible" : "compiled out")}.");
    }

    // ─── Menu Items ──────────────────────────────────────────────────────────

    [MenuItem("Tools/Build Stamp/Show Current Build Info")]
    private static void ShowCurrent()
    {
        var info = Read();
        EditorUtility.DisplayDialog(
            "Build Stamp",
            $"Version : {(string.IsNullOrEmpty(info.Version) ? PlayerSettings.bundleVersion : info.Version)}\n" +
            $"Build   : {info.BuildLabel}\n" +
            $"Date    : {(string.IsNullOrEmpty(info.Date) ? "—" : info.Date)}\n" +
            $"Platform: {(string.IsNullOrEmpty(info.Platform) ? "—" : info.Platform)}\n\n" +
            "The next build will be " + (info.Build + 1).ToString("D2") + ".",
            "OK");
    }

    [MenuItem("Tools/Build Stamp/Bump Build Number")]
    private static void Bump()
    {
        int build = Write(Read().Build + 1, EditorUserBuildSettings.activeBuildTarget.ToString());
        Debug.Log($"[BuildStamp] Build number bumped to {build:D2}.");
    }

    [MenuItem("Tools/Build Stamp/Reset Build Number To Zero")]
    private static void Reset()
    {
        if (!EditorUtility.DisplayDialog("Reset Build Number",
                "Set the build number back to 00? The next build will be 01.", "Reset", "Cancel"))
            return;

        Write(0, EditorUserBuildSettings.activeBuildTarget.ToString());
        Debug.Log("[BuildStamp] Build number reset to 00.");
    }

    // ─── Asset I/O ───────────────────────────────────────────────────────────

    private static BuildInfo Read()
    {
        var info = new BuildInfo();
        if (!File.Exists(AssetPath)) return info;

        foreach (string rawLine in File.ReadAllLines(AssetPath))
        {
            string line = rawLine.Trim();
            int split = line.IndexOf('=');
            if (split <= 0) continue;

            string key = line.Substring(0, split).Trim();
            string value = line.Substring(split + 1).Trim();

            switch (key)
            {
                case "version":  info.Version = value; break;
                case "build":    int.TryParse(value, out info.Build); break;
                case "date":     info.Date = value; break;
                case "platform": info.Platform = value; break;
            }
        }

        return info;
    }

    /// <summary>Writes the build info asset and imports it. Returns the number written.</summary>
    private static int Write(int build, string platform)
    {
        if (!Directory.Exists(ResourcesFolder)) Directory.CreateDirectory(ResourcesFolder);

        File.WriteAllText(AssetPath, string.Join("\n", new[]
        {
            "# Generated by BuildStampGenerator — do not edit by hand.",
            "version=" + PlayerSettings.bundleVersion,
            "build=" + build,
            "date=" + DateTime.Now.ToString("yyyy-MM-dd HH:mm"),
            "platform=" + platform,
            ""
        }));

        // Force a synchronous import so the freshly written asset is part of the
        // player data the build pipeline collects right after this callback. The
        // extra Refresh also drops the stale TextAsset the editor may still hold,
        // so the next Play session reads the new number instead of the old one.
        AssetDatabase.ImportAsset(AssetPath, ImportAssetOptions.ForceSynchronousImport);
        AssetDatabase.Refresh(ImportAssetOptions.ForceUpdate);
        return build;
    }

    private static bool IsDevelopmentBuild(BuildReport report)
        => (report.summary.options & BuildOptions.Development) != 0;
}
