using System;
using System.Collections.Generic;
using UnityEngine;

namespace LevelGenerationSystem
{
    /// <summary>
    /// Builds a level in the scene from a plain text layout file and a <see cref="TilePalette"/>.
    ///
    /// The text file is read line by line: each LINE is a row and each CHARACTER is a cell. The
    /// character is looked up in the palette and the matching prefab is instantiated. The first
    /// cell (row 0, column 0) is placed at <see cref="m_Origin"/> (default world origin 0,0,0);
    /// the level grows to the right (+X) and downward (-Y) so the text reads exactly as it looks
    /// in the file.
    ///
    /// Add this component to an empty GameObject, assign a level file + palette, then either press
    /// "Generate Level In Scene" in the inspector (edit time) or enable
    /// <see cref="m_GenerateOnAwake"/> to build at runtime.
    /// </summary>
    [DisallowMultipleComponent]
    public class TextLevelGenerator : MonoBehaviour
    {
        [Header("Input")]
        [Tooltip("Level layout text file. Each line is a row; each character is one cell.")]
        [SerializeField] private TextAsset m_LevelFile;

        [Tooltip("Maps characters in the text file to tile prefabs.")]
        [SerializeField] private TilePalette m_Palette;

        [Header("Placement")]
        [Tooltip("World position of the TOP-LEFT cell (row 0, column 0). " +
                 "The level grows right (+X) and down (-Y) from here.")]
        [SerializeField] private Vector3 m_Origin = Vector3.zero;

        [Tooltip("Optional parent for all generated tiles. If empty, tiles are parented under " +
                 "this GameObject.")]
        [SerializeField] private Transform m_TileParent;

        [Header("Runtime")]
        [Tooltip("If enabled, the level is generated automatically in Awake when playing.")]
        [SerializeField] private bool m_GenerateOnAwake = false;

        // Everything this component has spawned, so it can be cleared/regenerated cleanly.
        // Serialized (but hidden) so edit-time generated tiles are remembered across selections.
        [SerializeField, HideInInspector] private List<GameObject> m_Spawned = new List<GameObject>();

        /// <summary>The assigned layout file, or null.</summary>
        public TextAsset LevelFile => m_LevelFile;

        /// <summary>The assigned tile palette, or null.</summary>
        public TilePalette Palette => m_Palette;

        /// <summary>How many tiles are currently tracked as generated by this component.</summary>
        public int SpawnedCount => m_Spawned.Count;

        private void Awake()
        {
            if (m_GenerateOnAwake && Application.isPlaying)
                Generate();
        }

        /// <summary>Parent that generated tiles are nested under (the override, or this transform).</summary>
        public Transform ResolveParent() => m_TileParent != null ? m_TileParent : transform;

        /// <summary>
        /// Runtime convenience: generate using Object.Instantiate / Object.Destroy.
        /// Returns the number of tiles spawned, or -1 if input was invalid.
        /// </summary>
        public int Generate()
        {
            return Generate(
                prefab => Instantiate(prefab),
                go => Destroy(go));
        }

        /// <summary>
        /// Core generation routine. <paramref name="instantiate"/> and <paramref name="destroy"/>
        /// abstract HOW objects are created/removed so the same logic serves both runtime
        /// (Instantiate/Destroy) and the editor tool (PrefabUtility.InstantiatePrefab /
        /// Undo.DestroyObjectImmediate, which keeps prefab links and undo history).
        ///
        /// Any previously generated tiles are cleared first, so calling this repeatedly is safe.
        /// Returns the number of tiles spawned, or -1 if the palette or level file is missing.
        /// </summary>
        public int Generate(Func<GameObject, GameObject> instantiate, Action<GameObject> destroy)
        {
            if (instantiate == null) throw new ArgumentNullException(nameof(instantiate));
            if (destroy == null) throw new ArgumentNullException(nameof(destroy));

            if (m_Palette == null)
            {
                Debug.LogError("[TextLevelGenerator] No Tile Palette assigned.", this);
                return -1;
            }
            if (m_LevelFile == null)
            {
                Debug.LogError("[TextLevelGenerator] No Level File assigned.", this);
                return -1;
            }

            ClearGenerated(destroy);

            float size = m_Palette.TileSize;
            Transform parent = ResolveParent();
            string[] rows = SplitIntoRows(m_LevelFile.text);

            int count = 0;
            for (int row = 0; row < rows.Length; row++)
            {
                string line = rows[row];
                for (int col = 0; col < line.Length; col++)
                {
                    char c = line[col];
                    if (m_Palette.IsEmptySymbol(c)) continue;

                    if (!m_Palette.TryGetPrefab(c, out GameObject prefab))
                    {
                        Debug.LogWarning($"[TextLevelGenerator] No tile mapped for '{c}' at " +
                                         $"row {row}, column {col} — skipped.", this);
                        continue;
                    }

                    GameObject tile = instantiate(prefab);
                    if (tile == null) continue;

                    tile.transform.SetParent(parent, true);
                    tile.transform.position = m_Origin + new Vector3(col * size, -row * size, 0f);
                    m_Spawned.Add(tile);
                    count++;
                }
            }

            return count;
        }

        /// <summary>
        /// Destroys every tile this component has generated and clears the tracking list.
        /// <paramref name="destroy"/> chooses the destroy strategy (Destroy at runtime,
        /// Undo.DestroyObjectImmediate in the editor).
        /// </summary>
        public void ClearGenerated(Action<GameObject> destroy)
        {
            if (destroy == null) throw new ArgumentNullException(nameof(destroy));
            for (int i = m_Spawned.Count - 1; i >= 0; i--)
            {
                if (m_Spawned[i] != null)
                    destroy(m_Spawned[i]);
            }
            m_Spawned.Clear();
        }

        // Normalises line endings (\r\n, \r, \n) and splits into rows. A trailing blank final line
        // is dropped so an end-of-file newline doesn't add a phantom empty row.
        private static string[] SplitIntoRows(string text)
        {
            if (string.IsNullOrEmpty(text)) return Array.Empty<string>();

            string normalised = text.Replace("\r\n", "\n").Replace('\r', '\n');
            string[] rows = normalised.Split('\n');

            int length = rows.Length;
            if (length > 0 && rows[length - 1].Length == 0)
                length--;

            if (length == rows.Length) return rows;
            var trimmed = new string[length];
            Array.Copy(rows, trimmed, length);
            return trimmed;
        }
    }
}
